[package]
name = "enco"
version = "0.1.2"
edition = "2021"
description = "A simple entity-component library (not an ECS library!) for small projects."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
